#!/bin/bash

RABBITMQ_NODENAME=${RABBITMQ_NODENAME:-rabbit}

if [ -z "$CLUSTER_NODES" -o "$CLUSTER_WITH" = "$hostname" ]; then
  echo "Running as single server"
  rabbitmq-server
else
  echo "Running as clustered server"
  /usr/sbin/rabbitmq-server -detached
  rabbitmqctl stop_app

  echo "Detect which node to cluster with"
  IFS=', ' read -r -a array <<< "$CLUSTER_NODES"
  for element in "${array[@]}"
  do
    echo "Trying to cluster with node: $element"

    # TODO:
    # - check if $element is not the current container (via ping hostname? kube?)
    # - check if $element is available (via ping element? kube?)
    # if both are true:
    # rabbitmqctl join_cluster ${ENABLE_RAM:+--ram} $RABBITMQ_NODENAME@$element
    # rabbitmqctl start_app

  done  

  # Tail to keep the a foreground process active..
  tail -f /var/log/rabbitmq/*

fi